apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-file
  labels:
    app: upload-file
spec:
  selector:
    matchLabels:
      app: upload-file
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: upload-file
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: upload-file
        image: javierorta/upload-file:1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_REGION
            - name: AWS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_KEY
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET