apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
stringData:
  AWS_BUCKET: uploadfilesbbva
  AWS_REGION: us-east-1
  AWS_KEY: AKIAI2IY3BZLVOBOHE5Q
  AWS_SECRET: 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
